### ISSUE TITLE
MicroGate Geräte sollen unterstützt werden

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#601]

**Comment by mstenz** [comment]
I have tested the MicroGate Implementation with Rei2 und Racetime2, but it doesn't work. Needs checking
@richter-l Have you also tested it?

**Comment by richter-l** [comment]
Thanks for the report @mstenz!

The Racetime 2 uses an older protocol for the communication with the PC and is therefore not supported yet. I will open a new branch, which will add support for the older Microgate devices.

As with the Rei2, I just checked for old dump-files of an RT Pro and REI Pro device, and both appeared to be working fine for me with a build of the main branch. Would it be possible, that you provide me with the dump files of your Rei2 communication? The protocols for the Rei2 and the RT Pro and REI Pro should be all the same, but the professional devices from Microgate do allow for the emulation of other communication protocols, such as the one from ALGE and also different other variants of Microgate protocols. I am not familiar with the settings of the Rei 2, but I should be able to work it out with the communication log in the dump file.

Best regards!

**Comment by richter-l** [comment]
After a review (Thanks to @mstenz) it turned out to be an issue with the baudrate settings, which have to match in RH (currently hardcoded to 115200 for MG V2 devices, 9600 for MG V1 devices) and on the Timing Device. The issue will be adressed in the documentation.

In the future a "Baudrate setting" dialog may be added to the general settings to be able to resolve the issue without the necessity of changed settings on the timekeeping device.

I will also merge an update which adds support for the Racetime 2.

**Comment by svenflossmann** [comment]
Would consider as solved.
